db:
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver: org.postgresql.Driver
  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  hosts: ${DB_HOST},127.0.0.1
logging:
  file:
    name: spring.log
    path: /
  level:
    root: INFO
    org.springframework: INFO
    liquibase: DEBUG
spring:
  boot:
    admin:
      client:
        url: http://${ADMIN_SERVER_HOST}:${ADMIN_SERVER_PORT}
        instance:
          name: Rental of pets
          management-url: http://${ADMIN_SERVER_HOST}:${ADMIN_SERVER_PORT}/actuator
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
    default-schema: ${LIQUIBASE_DEFAULT_SCHEMA}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: ${MAIL_TIMEOUT}
          writetimeout: ${MAIL_WRITETIMEOUT}
          connectiontimeout: ${MAIL_CONNECTIONTIMEOUT}
          socketFactory:
            port: ${MAIL_PORT}
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
  jpa:
    properties.hibernate:
      batch_size: ${HIBERNATE_BATCH_SIZE}
      fetch_size: ${HIBERNATE_FETCH_SIZE}
      show_sql: ${HIBERNATE_SHOW_SQL}
      format_sql: ${HIBERNATE_FORMAT_SQL}
      hbm2ddl.auto: ${HIBERNATE_HBM2DDL_AUTO}
      default_schema: ${HIBERNATE_DEFAULT_SCHEMA}
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: ${GOOGLE_SCOPE}
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}
  messages:
    basename: ${MESSAGES_BASENAME}
    encoding: ${MESSAGES_ENCODING}

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
  api-docs:
    path: "/v3/api-docs"
  packages-to-scan: "org.yaroslaavl.webappstarter.http"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enabled: true
    endpoint:
      metrics:
        enabled: true
